[package]
name = "recovery"
edition.workspace = true
version.workspace = true

[dependencies]
sdk = { workspace = true }
host = { workspace = true }
node = { workspace = true }
thiserror = { workspace = true }
commonware-storage = { workspace = true }
commonware-runtime = { workspace = true }
commonware-codec = "2026.5.0"
commonware-utils = { workspace = true }
futures = "0.3"

[dev-dependencies]
directory = { workspace = true }
commonware-cryptography = { workspace = true }
upgrade = { workspace = true }
async-trait = { workspace = true }
sha2 = { workspace = true }
