#[allow(warnings, clippy::all)]
mod __ice_group_icon_8f6cad39 {
use super::*;
impl super::FilesView {
pub(super) fn __ice_component_use_3(&self, __ice_palette: __IcePalette, __ice_use_scope: ::std::string::String) -> __IceElement<'_, __FilesViewMessage> { let __component_content: __IceElement<'_, __FilesViewMessage> = {
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let __ice_node_scope = format!("{}/root", __ice_use_scope); { let mut __children: ::std::vec::Vec<__IceElement<'_, __FilesViewMessage>> = ::std::vec::Vec::new(); if ("warning" == "ink") { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:16", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[7]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!("warning" == "ink")) && ("warning" == "label")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:22", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[73]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!(("warning" == "ink") || ("warning" == "label"))) && ("warning" == "meta")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:28", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[71]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta"))) && ("warning" == "caption")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:34", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[70]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!(((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption"))) && ("warning" == "hint")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:40", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[72]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint"))) && ("warning" == "idle")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:46", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[74]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!(((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle"))) && ("warning" == "accent")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:52", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[16]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent"))) && ("warning" == "success")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:58", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[25]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!(((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent")) || ("warning" == "success"))) && ("warning" == "warning")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:64", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[30]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!((((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent")) || ("warning" == "success")) || ("warning" == "warning"))) && ("warning" == "danger")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:70", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[20]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if ((!(((((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent")) || ("warning" == "success")) || ("warning" == "warning")) || ("warning" == "danger"))) && ("warning" == "paper")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:76", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[38]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } if (!((((((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent")) || ("warning" == "success")) || ("warning" == "warning")) || ("warning" == "danger")) || ("warning" == "paper"))) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:82", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[5]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((13.0) as f32)) } };
__ice_rendered
}); } ::ui_lang_guest::wire::Node::Linear { max_width: ::std::option::Option::None, clip: false, key: __ice_node_scope.clone(), wrap: None, axis: ::ui_lang_guest::wire::Axis::Column, spacing: ::std::option::Option::None, padding: ::std::option::Option::None, width: ::std::option::Option::None, height: ::std::option::Option::None, align: ::std::option::Option::None, background: ::std::option::Option::None, border: ::std::option::Option::None, children: __children } } };
__ice_rendered
}; __component_content }
pub(super) fn __ice_component_use_11(&self, __ice_palette: __IcePalette, __ice_use_scope: ::std::string::String) -> __IceElement<'_, __FilesViewMessage> { let __component_content: __IceElement<'_, __FilesViewMessage> = {
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let __ice_node_scope = format!("{}/root", __ice_use_scope); { let mut __children: ::std::vec::Vec<__IceElement<'_, __FilesViewMessage>> = ::std::vec::Vec::new(); if ("warning" == "ink") { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:16", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[7]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!("warning" == "ink")) && ("warning" == "label")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:22", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[73]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(("warning" == "ink") || ("warning" == "label"))) && ("warning" == "meta")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:28", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[71]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta"))) && ("warning" == "caption")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:34", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[70]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption"))) && ("warning" == "hint")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:40", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[72]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint"))) && ("warning" == "idle")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:46", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[74]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle"))) && ("warning" == "accent")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:52", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[16]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent"))) && ("warning" == "success")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:58", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[25]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent")) || ("warning" == "success"))) && ("warning" == "warning")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:64", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[30]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!((((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent")) || ("warning" == "success")) || ("warning" == "warning"))) && ("warning" == "danger")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:70", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[20]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(((((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent")) || ("warning" == "success")) || ("warning" == "warning")) || ("warning" == "danger"))) && ("warning" == "paper")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:76", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[38]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if (!((((((((((("warning" == "ink") || ("warning" == "label")) || ("warning" == "meta")) || ("warning" == "caption")) || ("warning" == "hint")) || ("warning" == "idle")) || ("warning" == "accent")) || ("warning" == "success")) || ("warning" == "warning")) || ("warning" == "danger")) || ("warning" == "paper"))) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("folder")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:82", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[5]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } ::ui_lang_guest::wire::Node::Linear { max_width: ::std::option::Option::None, clip: false, key: __ice_node_scope.clone(), wrap: None, axis: ::ui_lang_guest::wire::Axis::Column, spacing: ::std::option::Option::None, padding: ::std::option::Option::None, width: ::std::option::Option::None, height: ::std::option::Option::None, align: ::std::option::Option::None, background: ::std::option::Option::None, border: ::std::option::Option::None, children: __children } } };
__ice_rendered
}; __component_content }
pub(super) fn __ice_component_use_12(&self, __ice_palette: __IcePalette, __ice_use_scope: ::std::string::String) -> __IceElement<'_, __FilesViewMessage> { let __component_content: __IceElement<'_, __FilesViewMessage> = {
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let __ice_node_scope = format!("{}/root", __ice_use_scope); { let mut __children: ::std::vec::Vec<__IceElement<'_, __FilesViewMessage>> = ::std::vec::Vec::new(); if ("label" == "ink") { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:16", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[7]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!("label" == "ink")) && ("label" == "label")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:22", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[73]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(("label" == "ink") || ("label" == "label"))) && ("label" == "meta")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:28", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[71]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!((("label" == "ink") || ("label" == "label")) || ("label" == "meta"))) && ("label" == "caption")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:34", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[70]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(((("label" == "ink") || ("label" == "label")) || ("label" == "meta")) || ("label" == "caption"))) && ("label" == "hint")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:40", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[72]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!((((("label" == "ink") || ("label" == "label")) || ("label" == "meta")) || ("label" == "caption")) || ("label" == "hint"))) && ("label" == "idle")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:46", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[74]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(((((("label" == "ink") || ("label" == "label")) || ("label" == "meta")) || ("label" == "caption")) || ("label" == "hint")) || ("label" == "idle"))) && ("label" == "accent")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:52", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[16]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!((((((("label" == "ink") || ("label" == "label")) || ("label" == "meta")) || ("label" == "caption")) || ("label" == "hint")) || ("label" == "idle")) || ("label" == "accent"))) && ("label" == "success")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:58", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[25]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(((((((("label" == "ink") || ("label" == "label")) || ("label" == "meta")) || ("label" == "caption")) || ("label" == "hint")) || ("label" == "idle")) || ("label" == "accent")) || ("label" == "success"))) && ("label" == "warning")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:64", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[30]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!((((((((("label" == "ink") || ("label" == "label")) || ("label" == "meta")) || ("label" == "caption")) || ("label" == "hint")) || ("label" == "idle")) || ("label" == "accent")) || ("label" == "success")) || ("label" == "warning"))) && ("label" == "danger")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:70", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[20]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if ((!(((((((((("label" == "ink") || ("label" == "label")) || ("label" == "meta")) || ("label" == "caption")) || ("label" == "hint")) || ("label" == "idle")) || ("label" == "accent")) || ("label" == "success")) || ("label" == "warning")) || ("label" == "danger"))) && ("label" == "paper")) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:76", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[38]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } if (!((((((((((("label" == "ink") || ("label" == "label")) || ("label" == "meta")) || ("label" == "caption")) || ("label" == "hint")) || ("label" == "idle")) || ("label" == "accent")) || ("label" == "success")) || ("label" == "warning")) || ("label" == "danger")) || ("label" == "paper"))) { __children.push({
let __ice_rendered: __IceElement<'_, __FilesViewMessage> = { let (__hash, __bytes) = ::ui_lang_guest::slots::picture(crate::host::icon(::std::convert::AsRef::as_ref(&("file")))); ::ui_lang_guest::wire::Node::Svg { inherit_button_ink: false, key: format!("{}/@media:82", __ice_use_scope), hash: __hash, bytes: __bytes, label: ::std::option::Option::None, color: ::std::option::Option::Some({ let __color: ::iced::Color = __ice_palette.colors[5]; ::ui_lang_guest::wire::Rgba([__color.r, __color.g, __color.b, __color.a]) }), hover: ::std::option::Option::None, fit: ::std::option::Option::None, rotation: ::std::option::Option::None, opacity: ::std::option::Option::None, width: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)), height: ::std::option::Option::Some(::ui_lang_guest::wire::Length::Fixed((16.0) as f32)) } };
__ice_rendered
}); } ::ui_lang_guest::wire::Node::Linear { max_width: ::std::option::Option::None, clip: false, key: __ice_node_scope.clone(), wrap: None, axis: ::ui_lang_guest::wire::Axis::Column, spacing: ::std::option::Option::None, padding: ::std::option::Option::None, width: ::std::option::Option::None, height: ::std::option::Option::None, align: ::std::option::Option::None, background: ::std::option::Option::None, border: ::std::option::Option::None, children: __children } } };
__ice_rendered
}; __component_content }
}
}
