app Ducktape
  title "Ducktape"
  theme app_theme
  bg app_background
  fg app_text
  id "dev.ducktape.app"
  font "../../../crates/design/assets/fonts/Geist[wght].ttf"
  font "../../../crates/design/assets/fonts/GeistMono[wght].ttf"
  font "../../../crates/design/assets/fonts/IBMPlexSansKR-Regular.ttf"
  font "../../../crates/design/assets/fonts/IBMPlexSansKR-Medium.ttf"
  font "../../../crates/design/assets/fonts/IBMPlexSansKR-SemiBold.ttf"
  text-size 13.5
  antialiasing true
  window
    size 1280 800
    min-size 820 540
    position centered
    platform macos
      title-hidden true
      titlebar-transparent true
      fullsize-content-view true

use "backend.ice"
use "ducktape-ui/default.ice"
use "theme.ice"
use "state.ice"
use "components/icon.ice"
use "components/kit.ice"
use "components/patterns.ice"
use "components/overlay.ice"
use "components/shell.ice"
use "components/onboarding.ice"
use "components/chat.ice"
use "components/dm.ice"
use "components/huddle.ice"
use "components/pages.ice"
use "components/forge.ice"
use "components/roster.ice"
use "components/files.ice"
use "components/node.ice"
use "screens/roster.ice"
use "screens/governance.ice"
use "screens/overlays.ice"
use "screens/storage.ice"
use "screens/settings.ice"
use "screens/forge.ice"
use "screens/pages.ice"
use "screens/chat.ice"
use "handlers/lifecycle.ice"
use "handlers/forge.ice"
use "handlers/files.ice"
use "handlers/roster.ice"
use "handlers/node.ice"
use "handlers/overlays.ice"
use "handlers/chat.ice"
use "handlers/pages.ice"
use "handlers/onboarding.ice"
use "handlers/huddle.ice"
use "view.ice"
use "tests.ice"
