impl Ducktape {
    fn native_view(
        &self,
    ) -> (
        crate::module_view::ViewSpec,
        fn(crate::module_view::ModuleViewEvent) -> __DucktapeMessage,
    ) {
        match self.shell_tab {
            ShellTab::Chat => (
                crate::module_view::chat_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    &self.connected_rpc,
                    &self.network_name,
                    &self.network_chain_id,
                    &self.status,
                    self.block_height,
                    &self.account_number,
                    &self.settings_user_key,
                    self.dm_peers_generation,
                    &self.rooms,
                    &self.dm_rows,
                    self.channel_create_open,
                    &self.active_channel,
                    &self.active_dm_peer,
                    &self.active_dm,
                    self.chat_land_seq,
                    self.unread_boundary,
                    self.mutation_phase.clone(),
                    self.loading,
                    self.huddle_joined,
                    &self.huddle_channel,
                    &self.huddle_channel_name,
                    self.huddle_joined_at,
                    self.huddle_now,
                    self.call_muted,
                    self.shift_held,
                    self.chat_copy_chord_serial,
                    self.chat_sent_serial,
                    &self.chat_pending_sends,
                    &self.live_agents,
                ),
                __DucktapeMessage::ChatViewEvent,
            ),
            ShellTab::Pages => (
                crate::module_view::pages_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    &self.network_chain_id,
                    &self.page_route,
                    self.page_route_serial,
                ),
                __DucktapeMessage::PagesViewEvent,
            ),
            ShellTab::Forge => (
                crate::module_view::forge_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    &self.network_name,
                    &self.account_bio,
                    &crate::backend::member_tier(&self.members_rows),
                    &self.network_chain_id,
                    &self.connected_rpc,
                    &self.forge_link,
                    self.forge_link_tick,
                ),
                __DucktapeMessage::ForgeViewEvent,
            ),
            ShellTab::Agents => (
                crate::module_view::agents_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    &self.account_number,
                    &self.agents_open_run,
                    self.agents_opened,
                ),
                __DucktapeMessage::AgentsViewEvent,
            ),
            ShellTab::Files => (
                crate::module_view::files_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    &self.network_chain_id,
                    &self.fs_route,
                    self.fs_route_serial,
                ),
                __DucktapeMessage::FilesViewEvent,
            ),
            ShellTab::Explorer => (
                crate::module_view::explorer_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    self.block_height,
                    &crate::backend::sync_label(
                        &self.node_phase,
                        self.node_sync_applied,
                        self.node_sync_target,
                    ),
                ),
                __DucktapeMessage::ExplorerViewEvent,
            ),
            ShellTab::Node => (
                crate::module_view::node_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    crate::backend::members_is_admin(&self.members_rows),
                    &crate::backend::member_tier(&self.members_rows),
                    &self.status,
                    &self.node_data_dir,
                    self.wall_now,
                ),
                __DucktapeMessage::NodeViewEvent,
            ),
            ShellTab::Members => (
                crate::module_view::members_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    crate::backend::members_is_admin(&self.members_rows),
                ),
                __DucktapeMessage::MembersViewEvent,
            ),
            ShellTab::Governance => (
                crate::module_view::governance_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    crate::backend::members_is_admin(&self.members_rows),
                ),
                __DucktapeMessage::GovernanceViewEvent,
            ),
            ShellTab::Settings => (
                crate::module_view::settings_view(
                    *self.__ice_derived_dark(),
                    self.connected,
                    self.loading,
                    &self.status,
                    self.mutation_phase.clone(),
                    self.appearance.clone(),
                    self.desktop_notifications,
                    &self.password,
                    &self.settings_user_key,
                    &self.account_name,
                    &self.network_name,
                    &self.connected_rpc,
                    &self.account_ceremony_phase,
                    &self.account_ceremony_qr,
                    &self.account_ceremony_detail,
                    &self.account_ceremony_left,
                    &self.settings_key_state,
                    &self.settings_key_path,
                    &self.account_number,
                    self.account_exists,
                    self.account_busy,
                    &self.account_ticket,
                ),
                __DucktapeMessage::SettingsViewEvent,
            ),
        }
    }
}
