// GENERATED by `make stream-types` (bin/noded/src/stream.rs, bin/noded/src/lib.rs call-control types) — do not edit.

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type ClientMsg = { "op": "subscribe", topics: Array<string>, resume: { [key in string]: string }, } | { "op": "unsubscribe", topics: Array<string>, } | { "op": "termInput", session: string, data: string, } | { "op": "termResize", session: string, cols: number, rows: number, } | { "op": "termCommand", session: string, text: string, origin: string, };

export type ServerFrame = { "type": "subscribed", topics: { [key in string]: string | null }, } | { "type": "event", topic: string, cursor: string, op: StreamOpRow, } | { "type": "termCommandLog", topic: string, seq: number, origin: string, text: string, } | { "type": "tail", topic: string, cursor: string, item: TailItem, } | { "type": "lagged", topic: string, cursor: string, } | { "type": "heartbeat", height: number, appHash: string, timeMs: number, intervalMs: number, } | { "type": "error", topic: string, code: StreamErrorCode, detail: string, };

export type StreamErrorCode = "unknownTopic" | "unavailable" | "badCursor" | "badFrame";

export type StreamOpRow = { height: number, seq: number, time: number, origin: StreamOrigin, payload?: JsonValue, payloadHex?: string, };

export type StreamOrigin = { kind: StreamOriginKind, id?: string, };

export type StreamOriginKind = "external" | "module" | "system";

export type TailItem = { line: string, } | { height: number, time: number, message: string, baseSnapshot: string | null, paths: Array<string>, } | { stream: RunStream, line: string, } | { timeMs: number, text: string, };

export type RunStream = "stdout" | "stderr";

export type CallClientControl = { "type": "recipients", peers: Array<string>, } | { "type": "beacon", muted: boolean, cameraOn: boolean, sharing: boolean, } | { "type": "keyframeRequest", peer: string, };

export type CallServerControl = { "type": "keyframeRequest" } | { "type": "peerBeacon", peer: string, muted: boolean, cameraOn: boolean, sharing: boolean, } | { "type": "rateHint", maxKbps: number, };

