//! spawn the node as a detached orphan.
//!
//! the app talks to `ducktape-node` — the networked validator serving the
//! http/ws app surface. on first run a solo config is generated: a REAL
//! 1-validator consensus network (not an embedded fallback), so everything
//! the app writes is consensus state from day one.
//!
//! binary resolution, in order: the `DUCKTAPE_NODE_BIN` env override, then
//! `ducktape-node` next to this executable — which covers BOTH builds: in dev
//! the workspace target dir holds the binaries side by side (run
//! `bun run sidecar` once), and in the bundle tauri's externalBin places the
//! sidecar next to the app executable. the legacy embedded daemon
//! (`DUCKTAPE_NODED_BIN` / `ducktape-noded`) remains a fallback while it is
//! being retired.
//!
//! detaching: on unix the child gets its own process group, so a terminal
//! Ctrl-C to `tauri dev` (or the app quitting) never signals it; on windows
//! DETACHED_PROCESS + CREATE_NEW_PROCESS_GROUP is the equivalent. stdio goes
//! to a log file under app-data. the tauri shell plugin's sidecar API is NOT
//! used on purpose — it kills children when the app exits.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use tauri::Manager as _;

/// launch the node detached, storage + config + log under the OS app-data
/// dir; `listen` is the http/ws app-surface address the webview will poll.
/// returns the daemon's log path.
#[tauri::command]
pub fn daemon_spawn(app: tauri::AppHandle, listen: String) -> Result<String, String> {
    let data_dir = app
        .path()
        .app_data_dir()
        .map_err(|err| format!("no app-data dir: {err}"))?;
    let node_dir = data_dir.join("node");
    fs::create_dir_all(&node_dir).map_err(|err| format!("create {node_dir:?}: {err}"))?;

    let log_path = node_dir.join("daemon.log");
    let log = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&log_path)
        .map_err(|err| format!("open {log_path:?}: {err}"))?;
    let log_err = log.try_clone().map_err(|err| err.to_string())?;

    let mut cmd = match node_binary()? {
        NodeBinary::Node(binary) => {
            let config = ensure_solo_config(&node_dir, &listen)?;
            let mut cmd = Command::new(binary);
            cmd.arg("--config").arg(config);
            cmd
        }
        NodeBinary::LegacyNoded(binary) => {
            let mut cmd = Command::new(binary);
            cmd.arg("--listen")
                .arg(&listen)
                .arg("--storage")
                .arg(node_dir.join("storage"));
            cmd
        }
    };
    cmd.stdin(Stdio::null()).stdout(log).stderr(log_err);
    detach(&mut cmd);
    cmd.spawn()
        .map_err(|err| format!("spawn {:?}: {err}", cmd.get_program()))?;

    Ok(log_path.display().to_string())
}

/// write the solo network config on first run; an existing config is
/// respected as-is (user edits — peers, ports — survive restarts).
fn ensure_solo_config(node_dir: &Path, http_listen: &str) -> Result<PathBuf, String> {
    let path = node_dir.join("node.toml");
    if path.exists() {
        return Ok(path);
    }
    let storage = node_dir.join("storage");
    // toml literal strings: no escape handling for windows path separators.
    let config = format!(
        r#"# generated by the ducktape app: a solo (1-validator) local network.
# this node IS a consensus network of one — every submit is a finalized block.
id = 0
listen = "127.0.0.1:0"
namespace = "ducktape-local"
peer_seeds = [0]
validator_seeds = [0]
storage_dir = '{}'
http_listen = "{}"
"#,
        storage.display(),
        http_listen,
    );
    fs::write(&path, config).map_err(|err| format!("write {path:?}: {err}"))?;
    Ok(path)
}

/// which binary [`node_binary`] resolved — the networked node takes a config
/// file; the retiring embedded daemon takes --listen/--storage.
enum NodeBinary {
    Node(PathBuf),
    LegacyNoded(PathBuf),
}

/// find the node binary (see module docs for the resolution order).
///
/// a sibling must pass [`usable`]: tauri copies the externalBin entry next
/// to the app executable, and if the sidecar was never staged that copy is
/// build.rs's EMPTY placeholder — spawning it fails with a baffling
/// permission-denied. reject it here with an actionable message instead.
fn node_binary() -> Result<NodeBinary, String> {
    if let Ok(explicit) = std::env::var("DUCKTAPE_NODE_BIN") {
        return Ok(NodeBinary::Node(PathBuf::from(explicit)));
    }
    let exe = std::env::current_exe().map_err(|err| err.to_string())?;
    let dir = exe
        .parent()
        .ok_or_else(|| "app executable has no parent dir".to_string())?;
    let sibling = dir.join(format!("ducktape-node{}", std::env::consts::EXE_SUFFIX));
    if usable(&sibling) {
        return Ok(NodeBinary::Node(sibling));
    }
    if let Ok(explicit) = std::env::var("DUCKTAPE_NODED_BIN") {
        return Ok(NodeBinary::LegacyNoded(PathBuf::from(explicit)));
    }
    let legacy = dir.join(format!("ducktape-noded{}", std::env::consts::EXE_SUFFIX));
    if usable(&legacy) {
        return Ok(NodeBinary::LegacyNoded(legacy));
    }
    Err(format!(
        "no usable ducktape-node at {} — stage it with `bun run sidecar` \
         (or `make sidecar` at the repo root), or set DUCKTAPE_NODE_BIN",
        sibling.display()
    ))
}

/// resolve the networked `ducktape-node` binary path for the workspace flow:
/// the `DUCKTAPE_NODE_BIN` override, else the sibling next to this executable.
/// unlike [`node_binary`] there is no legacy-noded fallback — workspaces always
/// run the network-shape node (real identity, real descriptor).
pub(crate) fn resolve_node_bin() -> Result<PathBuf, String> {
    if let Ok(explicit) = std::env::var("DUCKTAPE_NODE_BIN") {
        return Ok(PathBuf::from(explicit));
    }
    let exe = std::env::current_exe().map_err(|err| err.to_string())?;
    let dir = exe
        .parent()
        .ok_or_else(|| "app executable has no parent dir".to_string())?;
    let sibling = dir.join(format!("ducktape-node{}", std::env::consts::EXE_SUFFIX));
    if usable(&sibling) {
        return Ok(sibling);
    }
    Err(format!(
        "no usable ducktape-node at {} — stage it with `bun run sidecar` \
         (or `make sidecar` at the repo root), or set DUCKTAPE_NODE_BIN",
        sibling.display()
    ))
}

/// a real node binary: present, non-empty, executable.
fn usable(path: &PathBuf) -> bool {
    let Ok(meta) = fs::metadata(path) else {
        return false;
    };
    if !meta.is_file() || meta.len() == 0 {
        return false;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        meta.permissions().mode() & 0o111 != 0
    }
    #[cfg(not(unix))]
    {
        true
    }
}

#[cfg(unix)]
pub(crate) fn detach(cmd: &mut Command) {
    use std::os::unix::process::CommandExt as _;
    // own process group: terminal signals aimed at the app never reach it
    cmd.process_group(0);
}

#[cfg(windows)]
pub(crate) fn detach(cmd: &mut Command) {
    use std::os::windows::process::CommandExt as _;
    const DETACHED_PROCESS: u32 = 0x0000_0008;
    const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
    cmd.creation_flags(DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP);
}
