[package]
name = "saga"
edition.workspace = true
version.workspace = true

[dependencies]
sdk = { workspace = true }
saga-interface = { workspace = true }
valset-interface = { workspace = true }
capability-interface = { workspace = true }
sha2 = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
futures = "0.3"
host = { workspace = true }
valset = { workspace = true }
