package ducktape:view@1.0.0;

world view {
    import panicked: func(message: string);
    export init: func();
    export tick: func(events: list<u8>) -> result<list<u8>, string>;
    export snapshot: func() -> result<list<u8>, string>;
    export restore: func(state: list<u8>) -> result<_, string>;
}
